spring:
  datasource:
    url: jdbc:mysql://localhost:3306/articket
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  profiles:
    include:
      - secret
      - cors

cloud:
  aws:
    s3:
      bucket: articketbuket
      base-url: https://articketbuket.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: AKIAYJ77X7CI7Q7QBJIC
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false