spring:
  security:
    datasource:
      url: # db주소
      username: # db이름
      password: # db비밀번호
    oauth2:
      jwt:
        secret: # jwt secret key
      provider:
        kakao:
          client-id: # Rest Api key
          client-secret: # client secret

cloud:
  aws:
    s3:
      credentials:
        access-key: # s3 access-key
        secret-key: # s3 secret-key
