spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE


  profiles:
    include:
      - secret
      - cors


cloud:
  aws:
    s3:
      bucket: articketbuket
      base-url: https://articketbuket.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

default-profile-url: https://articketbuket.s3.ap-northeast-2.amazonaws.com/defaultProfile.jpg

external-service-url: http://i10a704.p.ssafy.io:8082

recommend-server-url: http://i10a704.p.ssafy.io:8083
recommend-shorts-path: /shorts/recommend

server:
  port: 8081
