spring:
  datasource:
    url: jdbc:mysql://localhost:3306/articket
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  profiles:
    include:
      - secret
      - cors
