spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  profiles:
    include:
      - secret
      - cors

